- hosts: localhost

  vars:
    proxy_env:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
      TERM: xterm-256color
      SHELL: /bin/bash

  tasks:

    - name: wersja kasnet
      shell: mysql -N -e "select wartosc from KasyUstawienia where parametr='Wersja' order by czas desc limit 1;" kasa
      register: ver_df_daemon
      environment: "{{ proxy_env }}"

    - name: wersja xasnet
      shell: mysql -N -e "select wartosc from KasyUstawienia where parametr='Klient.Wersja' order by czas desc limit 1;" kasa
      register: ver_xkasnet
      environment: "{{ proxy_env }}"

    - name: unhold paczek xkasnet'a
      shell: |
          sudo apt-mark unhold $(apt-mark showhold)
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      ignore_errors: yes

    - name: Sprawdzam z jakim configiem uruchomiona jest kasa
      shell: |
         ps aux | grep "kasa.config" |grep -v grep | awk '{print $NF}'
      register: POSconfig

    - name: fail
      shell: echo "bledny config"
      failed_when: "'{{ POSconfig.stdout }}' == 'kasa.config-1700x1200-eciph-new-layout' or '{{ POSconfig.stdout }}' == 'kasa.config-1700x1200-eceuro'"

    - name:  Instalacja paczek xkasnet bionic
      apt:
        name:
          - xkasnet-client-2.2.18=2.2.18r202311021233~bionic-1
          - xkasnet-client-ec-2.2.18=2.2.18r202311021233~bionic-1
          - xkasnet-libnative-jni-2.2.18=2.2.18r202311021233~bionic-1
        state: present
        #state: latest
        force: yes
        update_cache: yes
      when: ver_xkasnet.stdout != '2.2.18r202311021233' and ansible_distribution_version == '18.04' and '{{ POSconfig.stdout }}' != 'kasa.config-1700x1200-eceuro'
      register: upgrade_xkasnet
      environment: "{{ proxy_env }}"

    - name:  Instalacja paczek xkasnet jammy
      apt:
        name:
          - xkasnet-client-2.2.18=2.2.18r202309010916~jammy-1
          - xkasnet-client-ec-2.2.18=2.2.18r202309010916~jammy-1
          - xkasnet-libnative-jni-2.2.18=2.2.18r202309010916~jammy-1
        state: present
        #state: latest
        force: yes
        update_cache: yes
      when: ver_xkasnet.stdout != '2.2.18r202309010916' and ansible_distribution_version == '22.04'
      register: upgrade_xkasnet
      environment: "{{ proxy_env }}"

    - name: Sprawdzam czy jest config xkasnet'a
      stat:
        path: '/home/kasa/CONFIG'
      register: stat_result

    - name: Tworze config kasy jezeli nie ma - new layout
      ansible.builtin.lineinfile:
        path: '/home/kasa/CONFIG'
        line: '{{ POSconfig.stdout }}-new-layout'
        create: yes
      when: not stat_result.stat.exists

    - name: Zmiana configa na nowy layout
      replace:
        path: '/home/kasa/CONFIG'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.line }}'
        backup: yes
      with_items:
        - { regexp: '^kasa.*$', line: '{{ POSconfig.stdout }}-new-layout' }
      when: stat_result.stat.exists and POSconfig.stdout is not search("kasa.*-new-layout") and '{{ POSconfig.stdout }}' != 'kasa.config-1700x1200-eceuro'

    - name: Zmiana configa na nowy layout
      replace:
        path: '/home/kasa/CONFIG'
        regexp: '{{ item.regexp }}'
        replace: '{{ item.line }}'
        backup: yes
      with_items:
        - { regexp: '^kasa.*$', line: 'kasa.config-1700x1200-ecabc-new-layout' }
      when: stat_result.stat.exists and POSconfig.stdout is not search("kasa.*-new-layout") and '{{ POSconfig.stdout }}' == 'kasa.config-1700x1200-eciph-new-layout'

    - name: Usuwam .cache
      file:
        state: absent
        path: '/home/xkasnet/.cache'
      ignore_errors: yes

    - name: Zmieniam ownera na xkasnet
      file:
        path: /home/xkasnet
        state: directory
        recurse: yes
        owner: user
        group: user
      ignore_errors: yes

    - name:  Instalacja paczek kasnet bionic
      apt:
        name:
          - kasnet-libwaga-2.1.337=2.1.337r202303221358~bionic-1
          - kasnet-server-2.1.337=2.1.337r202303221358~bionic-1
          - kasnet-src-2.1.337=2.1.337r202303221358~bionic-1
          - kasnet-config-2.1.337=2.1.337r202303221358~bionic-1
          - kasnet-tools-2.1.337=2.1.337r202303221358~bionic-1
          - kasnet-monitor-2.1.337=2.1.337r202303221358~bionic-1
        state: present
        force: yes
        update_cache: yes
      when: ver_df_daemon.stdout != '2.1.337r202303221358' and ansible_distribution_version == '18.04'
      register: upgrade_df_daemon
      environment: "{{ proxy_env }}"

    - name:  Instalacja paczek kasnet jammy
      apt:
        name:
          - kasnet-libwaga-2.1.337=2.1.337r202303221358~jammy-1
          - kasnet-server-2.1.337=2.1.337r202303221358~jammy-1
          - kasnet-src-2.1.337=2.1.337r202303221358~jammy-1
          - kasnet-config-2.1.337=2.1.337r202303221358~jammy-1
          - kasnet-tools-2.1.337=2.1.337r202303221358~jammy-1
          - kasnet-monitor-2.1.337=2.1.337r202303221358~jammy-1
        state: present
        force: yes
        update_cache: yes
      when: ver_df_daemon.stdout != '2.1.337r202303221358' and ansible_distribution_version == '22.04'
      register: upgrade_df_daemon
      environment: "{{ proxy_env }}"

    - name: port waga
      stat:
        path: /dev/ttyUSB_WAGA
      register: file_data

    # - name: Wylaczam waga
    #   replace:
    #     backup: true
    #     path: '//home/kasa/konfiguracja/zmienne.dat'
    #     regexp: "{{ item.regexp }}"
    #     replace: "{{ item.line }}"
    #   with_items:
    #     - { regexp: '(producent_wagi).([0-9])', line: '\1\t0' }
    #   when: not file_data.stat.exists

    - name:  Instalacja vrad
      apt:
        name:
          - vrad
        state: latest
        force: yes
        update_cache: yes
      environment: "{{ proxy_env }}"

    - name: hosts
      blockinfile:
        marker: "## {mark} RAD3"
        path: '/etc/hosts'
        block: |
         127.0.0.1  rad.mparagon.pl
      no_log: true

    - name: backup configa
      copy:
        src: /home/xkasnet/konfiguracja/.local
        dest: /home/xkasnet/konfiguracja/local-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}

    - name: konfiguracja local
      blockinfile:
        owner: user
        group: user
        backup: true
        create: true
        marker: "## {mark} RAD3"
        path: '/home/xkasnet/konfiguracja/.local'
        block: |
         menu4.el7.index=262
         menu4.el7.image=EC_promolist.png
         menu10.el7.index=265

         app.promotionCalculator.isActive=false
         app.promotionCalculator.showWindowAfterAddingClientCard=true
         app.rad3Promotion.timeout=0
         app.rad3Promotion.isActive=false
         app.rad3Promotion.calculateAfterEachProduct=false
         app.rad3Promotion.diagnosticSendInterval=60
         app.rad3Promotion.sendDiagnosticsWithRegistration=false
         app.rad3Promotion.rp.calculateAfterEachProduct=true

         app.rad3Promotion.resendRequestCount=3
         app.rad3Promotion.rp.timeout=200
         app.rad3Promotion.rp.resendCount=1
         app.opt.showCustomerCardNumber=true
      no_log: true
      when: "'app.rad3Promotion.register' not in lookup('file', '/home/xkasnet/konfiguracja/.local')"

    - name: process k
      shell: cd /home/kasa/; bin/df_daemon -sem |grep "Kasjer zalogowany" | awk '{print $3}'
      register: pk
      environment: "{{ proxy_env }}"

    - name: reload df
      shell: pkill -9 df_daemon
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      when: pk.stdout == 'WOLNY'
      ignore_errors: yes

    - name: reload xk
      shell: pkill -f 'java -jar xkasnet.jar'
      args:
        executable: /bin/bash
      environment: "{{ proxy_env }}"
      when: pk.stdout == 'WOLNY'
      ignore_errors: yes
